// generated by CommonLibrary.cmake, do not edit.

/**
 * @file include/cyme/api.h
 * Defines export visibility macros for library cyme.
 */

#ifndef CYME_API_H
#define CYME_API_H

#include <cyme/defines.h>

#if defined(_MSC_VER) || defined(__declspec)
#  define CYME_DLLEXPORT __declspec(dllexport)
#  define CYME_DLLIMPORT __declspec(dllimport)
#else // _MSC_VER
#  define CYME_DLLEXPORT
#  define CYME_DLLIMPORT
#endif // _MSC_VER

#if defined(CYME_STATIC)
#  define CYME_API
#elif defined(CYME_SHARED)
#  define CYME_API CYME_DLLEXPORT
#else
#  define CYME_API CYME_DLLIMPORT
#endif

#if defined(CYME_SHARED_INL)
#  define CYME_INL CYME_DLLEXPORT
#else
#  define CYME_INL CYME_DLLIMPORT
#endif

#endif
