// generated by CommonPackage.cmake, do not edit.

#ifndef cyme_DEFINES_Linux_H
#define cyme_DEFINES_Linux_H

#ifndef Linux
#  define Linux 1
#endif
#ifndef COMMON_USE_CXX11
#  define COMMON_USE_CXX11 1
#endif
#ifndef CYME_USE_BOOST
#  define CYME_USE_BOOST 1
#endif

#endif
